apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: techtrends
  name: techtrends
  namespace: staging
spec:
  replicas: 3
  selector:
    matchLabels:
      app: techtrends
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: techtrends
    spec:
      containers:
      - image: dalmaraya/techtrends:latest
        imagePullPolicy: IfNotPresent
        name: techtrends
        ports:
          - containerPort: 3111
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3111
          initialDelaySeconds: 3
          periodSeconds: 3
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3111
          initialDelaySeconds: 3
          periodSeconds: 3
        resources:
          requests:            
            memory: 90Mi
            cpu: 300m
          limits:
            memory: 128Mi
            cpu: 500m         